[project]
name = "youtube-video-summarization"
version = "0.1.0"
description = "Summarize and Chat with Youtube video"
readme = "README.md"
requires-python = "==3.12.9"
dependencies = [
    "pytubefix>=8.12.3",
]
